In [1]:
.3.import os
import zipfile
import pyarrow.parquet as pq
import pandas as pd

folder = r"F:\sanazi\python\data science\code\tamrin\proje\Tennis Schema\Tennis Schema\tennis_data"

data = {}

for file in os.listdir(folder): 
    if file.endswith(".zip"):

        zip_path = os.path.join(folder, file) 

        with zipfile.ZipFile(zip_path) as z: 
            for parquet_file in z.namelist(): 
                if parquet_file.endswith(".parquet"): 

                    with z.open(parquet_file) as f:
                        df = pq.read_table(f).to_pandas()
                    table_name =os.path.basename(os.path.dirname(parquet_file))[4:-8] + os.path.basename(parquet_file)[:-17]

                    if table_name not in data:
                        data[table_name] = [] 
                    data[table_name].append(df)

for table_name in data:
    data[table_name] = pd.concat(data[table_name], ignore_index=True) 

print(data.keys())

C:\Users\sepehr\AppData\Local\Temp\ipykernel_2556\2021478474.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data[table_name] = pd.concat(data[table_name], ignore_index=True)

dict_keys(['matchaway_team', 'matchaway_team_score', 'matchevent', 'matchhome_team', 'matchhome_team_score', 'matchround', 'matchseason', 'matchtime', 'matchtournament', 'matchvenue', 'oddsodds', 'point_by_pointpbp', 'statisticsstatistics', 'tennis_powerpower', 'votesvotes'])

In [2]:
home_score = data["matchhome_team_score"]

period_cols = ["period_1", "period_2", "period_3", "period_4", "period_5"]

home_score["sets_played"] = home_score[period_cols].notna().sum(axis=1)

print("Average number of sets:", home_score["sets_played"].mean())

print("\nDistribution:")
print(home_score["sets_played"].value_counts().sort_index())

Average number of sets: 2.0699294733249913

Distribution:
sets_played
0     3020
1      337
2    22971
3     8836
Name: count, dtype: int64

In [3]:
home_score[home_score["sets_played"] == 1].head()

,match_id,current_score,display_score,period_1,period_2,period_3,period_4,period_5,period_1_tie_break,period_2_tie_break,period_3_tie_break,period_4_tie_break,period_5_tie_break,normal_time,sets_played
243,12023465,1,1,6,None,None,None,None,None,None,None,None,None,None,1
400,12023465,1,1,6,None,None,None,None,None,None,None,None,None,None,1
543,12027667,0,0,2,None,None,None,None,None,None,None,None,None,None,1
611,12039218,0,0,3,None,None,None,None,None,None,None,None,None,None,1
647,12041662,0,0,4,None,None,None,None,None,None,None,None,None,None,1

In [4]:
home_score[home_score["sets_played"] == 0].head()

,match_id,current_score,display_score,period_1,period_2,period_3,period_4,period_5,period_1_tie_break,period_2_tie_break,period_3_tie_break,period_4_tie_break,period_5_tie_break,normal_time,sets_played
0,11974053,3,3,None,None,None,None,None,None,None,None,None,None,None,0
1,11974066,0,0,None,None,None,None,None,None,None,None,None,None,None,0
44,12001976,1,1,None,None,None,None,None,None,None,None,None,None,None,0
63,12002078,3,3,None,None,None,None,None,None,None,None,None,None,None,0
64,12002109,0,0,None,None,None,None,None,None,None,None,None,None,None,0

In [ ]:
import pandas as pd


home_score = data["matchhome_team_score"].copy()


period_cols = ["period_1", "period_2", "period_3", "period_4", "period_5"]


home_score["sets_played"] = home_score[period_cols].notna().sum(axis=1)


home_score_clean = home_score[home_score["sets_played"] >= 2]


print("Average number of sets:", home_score_clean["sets_played"].mean())


print("\nDistribution:")
print(home_score_clean["sets_played"].value_counts().sort_index())

Average number of sets: 2.277800484170151

Distribution:
sets_played
2    22971
3     8836
Name: count, dtype: int64