In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [2]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [26]:
query = """
    SELECT AVG(break_games_count) AS avg_break_games_per_match
    FROM (
        SELECT match_id, COUNT(*) AS break_games_count
        FROM (
            SELECT match_id, game_id
            FROM game_point_by_point
            WHERE serving != scoring
            GROUP BY match_id, game_id
        )
        GROUP BY match_id
    )
"""
df = con.execute(query).df()
df

   avg_break_games_per_match
0                   5.476151