In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [4]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb')
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [13]:
query = """
    SELECT home_player_id, away_player_id
    FROM v_match_overview
"""

In [14]:
df = con.execute(query).df()
df

       home_player_id  away_player_id
0              131442           88992
1              264344          163480
2               46390           80665
3               39712          387400
4               39711          251784
...               ...             ...
35048            <NA>            <NA>
35049            <NA>            <NA>
35050            <NA>            <NA>
35051            <NA>            <NA>
35052            <NA>            <NA>

[35053 rows x 2 columns]

In [16]:
df1 = df['home_player_id']
df2 = df['away_player_id']

count = (
    pd.concat([df1,df2], ignore_index=True)
    .dropna()
    .nunique()
)

count

2644

In [ ]:
# another way to compute:
# query3 = """
#     SELECT DISTINCT player_id
#     FROM match_home_team
# """
# query4 = """
#     SELECT DISTINCT player_id
#     FROM match_away_team
# """
# df3 = con.execute(query3).df()
# df4 = con.execute(query4).df()
# conc1 = pd.concat([df3,df4], ignore_index=True).nunique()
# conc1