In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [2]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [3]:
query1 = """
    SELECT DISTINCT player_id, weight
    FROM match_home_team
    WHERE weight IS NOT NULL
"""
query2 = """
    SELECT DISTINCT player_id, weight
    FROM match_away_team
    WHERE weight IS NOT NULL
"""

In [4]:
df1 = con.execute(query1).df()
df2 = con.execute(query1).df()

conc = pd.concat([df1,df2], ignore_index=True)
conc

      player_id  weight
0         19704      63
1         66874      74
2        189311      70
3        217883      80
4        248846      78
...         ...     ...
1257     213979      72
1258     232059      93
1259     235930      29
1260      65576      78
1261     224038      81

[1262 rows x 2 columns]

In [5]:
conc['weight'].mean()

np.float64(75.29318541996831)