In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [2]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [5]:
query1 = """
    SELECT
        player_id,
        weight,
        height,
        weight / POWER(height, 2) AS bmi
    FROM match_home_team
    WHERE weight IS NOT NULL
      AND height IS NOT NULL
      AND height > 0
"""
query2 = """
    SELECT
        player_id,
        weight,
        height,
        weight / POWER(height, 2) AS bmi
    FROM match_away_team
    WHERE weight IS NOT NULL
      AND height IS NOT NULL
      AND height > 0
"""

In [8]:
df1 = con.execute(query1).df()
df2 = con.execute(query2).df()

conc = pd.concat([df1,df2], ignore_index=True).drop_duplicates(subset=["player_id"]).copy()
conc

       player_id  weight  height        bmi
0          64580      85    1.88  24.049344
1         264344      70    1.85  20.452885
2          32466      65    1.68  23.030045
3          39712      83    1.88  23.483477
4          63642      79    1.88  22.351743
...          ...     ...     ...        ...
12255     192852      72    1.83  21.499597
12270      98981      72    1.80  22.222222
12445     113859      80    1.96  20.824656
12827      15733      73    1.78  23.040020
13223     162144      70    1.85  20.452885

[663 rows x 4 columns]

In [9]:
conc['bmi'].mean()

np.float64(22.479309039960736)