In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [3]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [23]:
query1 = """
    SELECT DISTINCT player_id, height
    FROM match_home_team
    WHERE height IS NOT NULL
"""
query2 = """
    SELECT DISTINCT player_id, height
    FROM match_away_team
    WHERE height IS NOT NULL
"""

In [24]:
df1 = con.execute(query1).df()
df2 = con.execute(query1).df()

conc = pd.concat([df1,df2], ignore_index=True)
conc

      player_id  height
0         32466    1.68
1         16683    1.83
2         75813    1.93
3        329816    1.85
4        217464    1.68
...         ...     ...
2529     113889    1.96
2530     321789    1.75
2531     155684    1.78
2532     272633    1.83
2533      41372    1.57

[2534 rows x 2 columns]

In [29]:
conc['height'].mean()

np.float64(1.822533543804262)