In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import duckdb

In [2]:
con = duckdb.connect(r'C:\Users\marzieh\Documents\GitHub\Tennis-project\data\tennis.duckdb', read_only=True)
con.execute("SHOW TABLES").df()

                      name
0              _build_info
1            _import_audit
2            _schema_audit
3            _source_files
4      game_point_by_point
5         match_away_score
6          match_away_team
7              match_event
8         match_home_score
9          match_home_team
10             match_round
11            match_season
12              match_time
13        match_tournament
14             match_venue
15             match_votes
16                    odds
17       period_statistics
18                   power
19  v_match_event_readable
20        v_match_overview

In [3]:
query1 = """
    SELECT DISTINCT player_id, height
    FROM match_home_team
    WHERE height IS NOT NULL
"""
query2 = """
    SELECT DISTINCT player_id, height
    FROM match_away_team
    WHERE height IS NOT NULL
"""

In [7]:
df1 = con.execute(query1).df()
df2 = con.execute(query2).df()

conc = pd.concat([df1,df2], ignore_index=True).drop_duplicates(subset=["player_id"]).copy()
conc

      player_id  height
0        264344    1.85
1         19704    1.81
2         95939    1.88
3        179262    1.96
4         19957    1.85
...         ...     ...
2496      42289    1.71
2530     412818    1.80
2536     246084    1.70
2542     234896    1.80
2543     407928    1.80

[1349 rows x 2 columns]

In [8]:
conc['height'].mean()

np.float64(1.8216530763528538)